#!/bin/bash

if [ ! $(command -v singularity) ]; then
	module load singularity
fi

VERSION=4.1.9.0
PACKAGE=GATK
TOOL=gatk
DIRECTORY=/opt/packages/$PACKAGE/$VERSION

PERSISTENT_FILE_STORAGE=/ocean
if [ ! -d $PERSISTENT_FILE_STORAGE ]; then
	singularity exec $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
else
	singularity exec -B $PERSISTENT_FILE_STORAGE $DIRECTORY/singularity-$PACKAGE-$VERSION.sif $TOOL "$@"
fi
